name: Create Release

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} || cd build  || make doc

    - name: Create Artifacts
      run: tar -czf release.tar.gz build/bin build/lib build/doc

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz"
        bodyFile: "README.md"